In [1]:
import numpy as np

# stoichiometry matrix
# CO, S, COads, Cads, Oads, H2, H2O, Hads, CHads, CH2ads, CH3ads, CH4
nu=np.array([[-1, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, -1, -1, 1, 0, 0, 0, 0, 0], [0, -2, 0, 0, 0, -1, 0, 2, 0, 0, 0, 0], [0, 1, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, -1, -1, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, -1, 0, -1, 1,0], [0, 2, 0, 0, 0, 0, 0, -1, 0, 0, -1, 1]])

print('stoichiometry matrix =')
print(nu)

size = nu.shape
print('matrix size =')
print(size)

rank = np.linalg.matrix_rank(nu)
print('matrix rank =')
print(rank)



stoichiometry matrix =
[[-1 -1  1  0  0  0  0  0  0  0  0  0]
 [ 0 -1 -1  1  1  0  0  0  0  0  0  0]
 [ 0  1  0  0 -1 -1  1  0  0  0  0  0]
 [ 0 -2  0  0  0 -1  0  2  0  0  0  0]
 [ 0  1  0 -1  0  0  0 -1  1  0  0  0]
 [ 0  1  0  0  0  0  0 -1 -1  1  0  0]
 [ 0  1  0  0  0  0  0 -1  0 -1  1  0]
 [ 0  2  0  0  0  0  0 -1  0  0 -1  1]]
matrix size =
(8, 12)
matrix rank =
8
